/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DBEngine;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;
import model.ThongKe;
import model.VeXe;

/**
 *
 * @author PC
 */
public final class HomeADFrm extends javax.swing.JFrame {

    /**
     * Creates new form HomeADFrm
     */
    private ArrayList<ThongKe> thongkes;
    private final DefaultTableModel tblTKModel;
    //
    private ArrayList<NhanVien> nhanviens;
    private final DefaultTableModel tblCaModel;
    //
    private ArrayList<VeXe> vexes;
    private final DefaultTableModel tblVeModel;
    //
    private int selectedIndex;
    static String fileNameTK = "thongke.txt";
    static String fileNameNV = "nhanvien.txt";
    static String fileNameVS = "vexe.txt";
    private final DBEngine db = new DBEngine();

    public HomeADFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        thongkes = new ArrayList<>();
        tblTKModel = (DefaultTableModel) tblThongKe.getModel();

        nhanviens = new ArrayList<>();
        tblCaModel = (DefaultTableModel) tblCaTruc.getModel();

        vexes = new ArrayList<>();
        tblVeModel = (DefaultTableModel) tblQuanLyVe.getModel();
        docFileTK(fileNameTK);
        showData(thongkes, tblTKModel);
        docFileNV(fileNameNV);
        showData(nhanviens, tblCaModel);
        //fakeData();
        docFileVS(fileNameVS);
        showData(vexes, tblVeModel);
    }

    HomeADFrm(DangNhapFrm aThis, boolean rootPaneCheckingEnabled) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public final <T> void showData(ArrayList<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        for (T t : list) {
            if (t instanceof NhanVien s) {
                model.addRow(new Object[]{s.getTenNV(), s.getKhu(),
                    s.getCaTruc(), s.getNgayTruc()
                });

            }
            if (t instanceof VeXe vs) {
                model.addRow(new Object[]{
                    vs.getMaVe(), vs.getTenVe(), vs.getGiaTien()
                });
            }
            if (t instanceof ThongKe vs) {
                model.addRow(new Object[]{
                    vs.getKhuVuc(), vs.getTongTien(), vs.getNgay()
                });
            }
        }

    }
//    phương thức thêm nhân viên ở frm add ca trực

    public void addCaTruc(NhanVien e) {
        nhanviens.add(e);
        showData(nhanviens, tblCaModel);

    }

    //phương thức sửa nhân viên ở frm sửa ca trực
    public void suaNhanVien(NhanVien e) {
        nhanviens.remove(selectedIndex);
        this.addCaTruc(e);

    }

    public void suaVeXe(VeXe vs) {
        vexes.remove(selectedIndex);
        vexes.add(vs);
        showData(vexes, tblVeModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCaTruc = new javax.swing.JTable();
        ThemCa = new javax.swing.JButton();
        XoaCa = new javax.swing.JButton();
        SuaCa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQuanLyVe = new javax.swing.JTable();
        SuaVe = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TimKiemNgay = new javax.swing.JButton();
        txtNgay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTien = new javax.swing.JTextField();
        Load = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCaTruc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên Nhân Viên", "Khu trực", "Ca trực", "Ngày trực"
            }
        ));
        jScrollPane1.setViewportView(tblCaTruc);

        ThemCa.setText("Thêm ca trực");
        ThemCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemCaActionPerformed(evt);
            }
        });

        XoaCa.setText("Xóa ca trực");
        XoaCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaCaActionPerformed(evt);
            }
        });

        SuaCa.setText("Sửa ca trực");
        SuaCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaCaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(ThemCa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(XoaCa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(SuaCa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemCa)
                    .addComponent(XoaCa)
                    .addComponent(SuaCa))
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Quản lý ca trực", jPanel1);

        tblQuanLyVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã vé", "Tên vé", "Giá tiền"
            }
        ));
        jScrollPane2.setViewportView(tblQuanLyVe);

        SuaVe.setText("Sửa vé");
        SuaVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(SuaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(SuaVe)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý vé xe", jPanel2);

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên khu vực", "Tổng tiền", "Ngày"
            }
        ));
        jScrollPane3.setViewportView(tblThongKe);

        jLabel1.setText("Chọn Ngày: ");

        TimKiemNgay.setText("Tìm kiếm");
        TimKiemNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemNgayActionPerformed(evt);
            }
        });

        txtNgay.setText("yyyy-mm-dd");
        txtNgay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgayMouseClicked(evt);
            }
        });

        jLabel2.setText("Tổng tiền: ");

        Load.setText("Load");
        Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTien))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(TimKiemNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Load)
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TimKiemNgay)
                    .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Load))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thống kê", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //them ca trực
    private void ThemCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemCaActionPerformed
        // TODO add your handling code here:
        AddCaTruc caTrucFrm = new AddCaTruc(this,
                rootPaneCheckingEnabled);
        caTrucFrm.setVisible(true);
        luuFile(nhanviens, fileNameNV);
    }//GEN-LAST:event_ThemCaActionPerformed
    //sửa ca trực
    private void SuaCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaCaActionPerformed
        // TODO add your handling code here:
        selectedIndex = tblCaTruc.getSelectedRow();
        if (nhanviens.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,
                    "Nhập thêm nhân viên!");
        } else if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(rootPane,
                    "Hãy chọn sinh viên!");
        } else {
            SuaCaTrucFrm suaCa = new SuaCaTrucFrm(this,
                    rootPaneCheckingEnabled);
            suaCa.setSuaCa(nhanviens.get(selectedIndex));
            suaCa.setVisible(true);
        }
        luuFile(nhanviens, fileNameNV);
    }//GEN-LAST:event_SuaCaActionPerformed
    // xóa ca trực nè
    private void XoaCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaCaActionPerformed
        // TODO add your handling code here:
        int removeIndex = tblCaTruc.getSelectedRow();
        if (removeIndex == -1) {
            JOptionPane.showMessageDialog(rootPane,
                    "Chọn Ca cần xóa!");
        } else if (nhanviens.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,
                    "Không có thông tin!");
        } else {
            nhanviens.remove(removeIndex);
            showData(nhanviens, tblCaModel);
        }
        luuFile(nhanviens, fileNameNV);
    }//GEN-LAST:event_XoaCaActionPerformed
    public void fakeData() {
        VeXe vs1 = new VeXe("vs1", "Xe Dap", 2000);
        vexes.add(vs1);
        VeXe vs2 = new VeXe("vs2", "Xe May", 5000);
        vexes.add(vs2);
        VeXe vs3 = new VeXe("vs3", "Ve Giao Vien", 0);
        vexes.add(vs3);
    }

    //sua ve  xe ne
    private void SuaVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaVeActionPerformed
        // TODO add your handling code here:

        selectedIndex = tblQuanLyVe.getSelectedRow();
        if (vexes.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,
                    "Nhập thêm ve xe!");
        } else if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(rootPane,
                    "Hãy chọn ve xe!");
        } else {
            SuaVeFrm suaVe = new SuaVeFrm(this,
                    rootPaneCheckingEnabled);
            suaVe.setSuaVe(vexes.get(selectedIndex));
            suaVe.setVisible(true);
        }

        luuFile(vexes, fileNameVS);
    }//GEN-LAST:event_SuaVeActionPerformed

    private void TimKiemNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemNgayActionPerformed
        // TODO add your handling code here:
        String ngay;
        float tongTien = 0;
        boolean check = false;
        ngay = txtNgay.getText();
        tblTKModel.setRowCount(0);
        for (ThongKe tk : thongkes) {
            if (ngay.equals(tk.getNgay())) {
                tblTKModel.addRow(new Object[]{
                    tk.getKhuVuc(), tk.getTongTien(), tk.getNgay()
                });
                tongTien += tk.getTongTien();
                check = true;
            }
        }
        txtTien.setText(Float.toString(tongTien));

        if (check == false) {
            JOptionPane.showMessageDialog(rootPane
            , "ngày đó không có doanh thu hoặc ngày nhâp không hợp lệ!");
            showData(thongkes, tblTKModel);
        }
    }//GEN-LAST:event_TimKiemNgayActionPerformed

    private void LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadActionPerformed
        // TODO add your handling code here:
        docFileTK(fileNameTK);
        showData(thongkes, tblTKModel);
    }//GEN-LAST:event_LoadActionPerformed
//  khi click chuột vào ngày trong bảng thống kê thì giá trị về null
    private void txtNgayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgayMouseClicked
        // TODO add your handling code here:
        txtNgay.setText("");
    }//GEN-LAST:event_txtNgayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeADFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeADFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeADFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeADFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HomeADFrm().setVisible(true);
            }
        });
    }

    public void luuFile(ArrayList T, String fileName) {
        try {
            db.writeToFile(T, fileName);
            System.out.println("Lưu file thành công");
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }
//đọc file lưu trở lại phòng thi

    public void docFileTK(String fileName) {
        try {
            thongkes = (ArrayList) db.readDataFromFile(fileName);
            System.out.println(" đọc được file");
        } catch (Exception ex) {
            System.out.println("không đọc được file");
        }
    }

    public void docFileNV(String fileName) {
        try {
            nhanviens = (ArrayList) db.readDataFromFile(fileName);
            System.out.println(" đọc được file");
        } catch (Exception ex) {
            System.out.println("không đọc được file");
        }
    }

    public void docFileVS(String fileName) {
        try {
            vexes = (ArrayList) db.readDataFromFile(fileName);
            System.out.println(" đọc được file");
        } catch (Exception ex) {
            System.out.println("không đọc được file");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Load;
    private javax.swing.JButton SuaCa;
    private javax.swing.JButton SuaVe;
    private javax.swing.JButton ThemCa;
    private javax.swing.JButton TimKiemNgay;
    private javax.swing.JButton XoaCa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCaTruc;
    private javax.swing.JTable tblQuanLyVe;
    private javax.swing.JTable tblThongKe;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtTien;
    // End of variables declaration//GEN-END:variables

}
