/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.NhanVien;

/**
 *
 * @author PC
 */
public class SuaCaTrucFrm extends javax.swing.JDialog {

    /**
     * Creates new form SuaCaTryuc
     */
    private HomeADFrm home;

    public SuaCaTrucFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocationRelativeTo(null);
        initComponents();
        home = (HomeADFrm) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SuaCa = new javax.swing.JButton();
        BoQua = new javax.swing.JButton();
        txtTenNV = new javax.swing.JTextField();
        txtNgayTruc = new javax.swing.JTextField();
        comBoKhu = new javax.swing.JComboBox<>();
        comBoCa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Sửa Ca Trực");

        jLabel2.setText("Tên nhân viên");

        jLabel3.setText("Khu trực");

        jLabel4.setText("Ca trực");

        jLabel5.setText("Ngày Trực");

        SuaCa.setText("Lưu");
        SuaCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaCaActionPerformed(evt);
            }
        });

        BoQua.setText("Hủy");
        BoQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoQuaActionPerformed(evt);
            }
        });

        txtNgayTruc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgayTrucMouseClicked(evt);
            }
        });
        txtNgayTruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayTrucActionPerformed(evt);
            }
        });

        comBoKhu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khu A", "Khu B", "Khu C" }));

        comBoCa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7h-15h", "15h-23h", "23h-7h" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comBoCa, 0, 129, Short.MAX_VALUE)
                    .addComponent(txtTenNV)
                    .addComponent(comBoKhu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayTruc)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(SuaCa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(BoQua, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comBoKhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comBoCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNgayTruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuaCa)
                    .addComponent(BoQua))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SuaCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaCaActionPerformed
        // TODO add your handling code here:
        String tenNV, khuTruc, caTruc, ngayTruc;
        tenNV = txtTenNV.getText();
        khuTruc = comBoKhu.getSelectedItem().toString();
        caTruc = comBoCa.getSelectedItem().toString();
        ngayTruc = txtNgayTruc.getText();
        boolean isOk = true;
        if (tenNV.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Họ tên không được để trống!");
            isOk = false;
        } else if (ngayTruc.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Ngay không được để trống!");
            isOk = false;
        } else if (tenNV.matches("[^a-zA-Z]+")) {
            JOptionPane.showMessageDialog(rootPane, "Họ tên chỉ chứa các chữ cái!");
            isOk = false;
        }
        //chekc ngay from ngày tháng 
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        dateFormat.setLenient(false); // Chặn việc chuyển đổi chuỗi không hợp lệ
        try {
            Date date = dateFormat.parse(ngayTruc);
            System.out.println("Ngày tháng hợp lệ: " + date);
        } catch (Exception e) {
            isOk = false;
            JOptionPane.showMessageDialog(rootPane, "Ngay tháng phải đẻ dạng YYYY-MM-DD!");
            System.out.println("Ngày tháng không hợp lệ: " + ngayTruc);
        }
        if (isOk) {
            NhanVien nv = new NhanVien(tenNV, tenNV, caTruc, khuTruc, ngayTruc);
            home.suaNhanVien(nv);
            JOptionPane.showMessageDialog(rootPane, "Sửa thành công!");
            this.dispose();
        }
    }//GEN-LAST:event_SuaCaActionPerformed

    private void BoQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoQuaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BoQuaActionPerformed

    private void txtNgayTrucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgayTrucMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayTrucMouseClicked

    private void txtNgayTrucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayTrucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayTrucActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaCaTrucFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaCaTrucFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaCaTrucFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaCaTrucFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SuaCaTrucFrm dialog = new SuaCaTrucFrm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoQua;
    private javax.swing.JButton SuaCa;
    private javax.swing.JComboBox<String> comBoCa;
    private javax.swing.JComboBox<String> comBoKhu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtNgayTruc;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables

    public void setSuaCa(NhanVien nv) {
        txtTenNV.setText(nv.getTenNV());
        txtNgayTruc.setText(nv.getNgayTruc());

    }
}
