/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.DBEngine;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.KhuVuc;
import model.ThongKe;
import model.VeXe;

/**
 *
 * @author PC
 */
public class TrongXeFrm extends javax.swing.JFrame {

    /**
     * Creates new form TrongXeFrm
     */
    ArrayList<KhuVuc> khuvucs;
    ArrayList<VeXe> vexes;
    ArrayList<ThongKe> thongkes;
    static String fileNameKV = "khuvuc.txt";
    static String fileNameVS = "vexe.txt";
    static String fileNameTK = "thongke.txt";
    private String nowDate;
    private final DBEngine db = new DBEngine();

    public TrongXeFrm() {
   
        initComponents();
        khuvucs = new ArrayList<KhuVuc>();
        vexes = new ArrayList<VeXe>();
        thongkes = new ArrayList<ThongKe>();
        this.setLocationRelativeTo(null);
//        docFileKV(fileNameKV);
//        docFileVS(fileNameVS);
//        docFileTK(fileNameTK);
//        fakeData();
//        fakeData2();
//        luuFile(vexes, fileNameKV);
//        luuFile(khuvucs, fileNameKV);
//        luuFile(thongkes, fileNameTK);
        LocalDate now = LocalDate.now();
        nowDate = now.toString();
//        nowDate = "2023-02-26";
        txtNgay.setText(nowDate);
        docFileKV(fileNameKV);
        docFileVS(fileNameVS);
        docFileTK(fileNameTK);
    }

    public void luuFile(ArrayList T, String fileName) {
        try {
            db.writeToFile(T, fileName);
            System.out.println("Lưu file thành công");
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }
//đọc file lưu trở lại phòng thi

    public void docFileKV(String fileName) {
        try {
            khuvucs = (ArrayList) db.readDataFromFile(fileName);
            System.out.println(" đọc được file");
        } catch (Exception ex) {
            System.out.println("không đọc được file");
        }
    }

    public void docFileVS(String fileName) {
        try {
            vexes = (ArrayList) db.readDataFromFile(fileName);
            System.out.println(" đọc được file");
        } catch (Exception ex) {
            System.out.println("không đọc được file");
        }
    }

    public void docFileTK(String fileName) {
        try {
            thongkes = (ArrayList) db.readDataFromFile(fileName);
            System.out.println(" đọc được file");
        } catch (Exception ex) {
            System.out.println("không đọc được file");
        }
    }

    public void fakeData() {
        VeXe vs1 = new VeXe("vs1", "Xe Dap", 2000);
        vexes.add(vs1);
        VeXe vs2 = new VeXe("vs2", "Xe May", 5000);
        vexes.add(vs2);
        VeXe vs3 = new VeXe("vs3", "Ve Giao Vien", 0);
        vexes.add(vs3);
    }

    public void fakeData2() {
        KhuVuc kv1 = new KhuVuc("Khu A");
        khuvucs.add(kv1);
        KhuVuc kv2 = new KhuVuc("Khu B");
        khuvucs.add(kv2);
        KhuVuc kv3 = new KhuVuc("Khu C");
        khuvucs.add(kv3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        thanhToan = new javax.swing.JButton();
        txtTongTien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        boxKhuVuc = new javax.swing.JComboBox<>();
        boxVeXe = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNgay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Quản Lý Trông Xe");

        thanhToan.setText("Thanh Toán");
        thanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanhToanActionPerformed(evt);
            }
        });

        jLabel2.setText("Tổng Tiền");

        boxKhuVuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khu A", "Khu B", "Khu C" }));

        boxVeXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe Dap", "Xe May", "Ve Giao Vien" }));

        jLabel3.setText("Khu vực:");

        jLabel4.setText("Loại vé:");

        txtNgay.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(thanhToan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boxKhuVuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxVeXe, 0, 155, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxVeXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thanhToan)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanhToanActionPerformed
        // TODO add your handling code here:
        docFileVS(fileNameVS);
        KhuVuc a = null;
        VeXe x = null;
        for (KhuVuc kv : khuvucs) {
            if (boxKhuVuc.getSelectedItem().toString().equalsIgnoreCase(kv.getKhuVuc())) {
                a = kv;
                break;
            }
        }
        for (VeXe vs : vexes) {
            if (boxVeXe.getSelectedItem().toString().equalsIgnoreCase(vs.getTenVe())) {
                x = vs;
                break;
            }
        }
        a.setTongTien(x);
        
        int t = 0;
        for(ThongKe item:thongkes){
            if(nowDate.equalsIgnoreCase(item.getNgay()) && 
                    item.getKhuVuc().equalsIgnoreCase(a.getKhuVuc())){
                item.setTongTien(a.getTongTien());
                t ++;
            }
        }
        if(t==0){
            a.setTongTien(x.getGiaTien());
            ThongKe tk = new ThongKe(nowDate , a.getTongTien() , a.getKhuVuc());
            thongkes.add(tk);
            
        }
        txtTongTien.setText(Float.toString(a.getTongTien()));
        JOptionPane.showMessageDialog(rootPane, "Done");

        luuFile(khuvucs, fileNameKV);
        luuFile(thongkes, fileNameTK);
    }//GEN-LAST:event_thanhToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrongXeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrongXeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrongXeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrongXeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HomeADFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxKhuVuc;
    private javax.swing.JComboBox<String> boxVeXe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton thanhToan;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
